from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class AgentConsultRequest(BaseModel):
    query: str = Field(..., min_length=3, description="Entrepreneur natural language request (e.g. 'I have ₹3 lakh and want to start a bakery in my village.')")
    pincode: Optional[str] = Field(None, description="6-digit postal code if known")
    village_town: Optional[str] = Field(None, description="Village or town name")
    district: Optional[str] = Field(None, description="District name")
    state: Optional[str] = Field(None, description="State name")
    business_category: Optional[str] = Field(None, description="Target enterprise sector (e.g. bakery, agro-repair, grocery)")
    available_capital: Optional[float] = Field(None, ge=0, description="Available entrepreneur equity in ₹")
    radius_km: Optional[float] = Field(3.0, gt=0, le=25.0, description="Competitor discovery radius in km")
    social_category: Optional[str] = Field("GENERAL", description="Social category for subsidy rules (GENERAL, OBC, SC, ST, WOMEN)")
    is_rural: Optional[bool] = Field(True, description="Whether the enterprise is situated in a rural village")

class ToolExecutionLog(BaseModel):
    tool_name: str
    input_args: Dict[str, Any]
    output_summary: str
    duration_ms: float
    success: bool
    error_message: Optional[str] = None

class AgentAdvisoryResponse(BaseModel):
    user_query: str
    executive_summary: str

    # Strict provenance segregation
    facts: Dict[str, Any] = Field(default_factory=dict, description="Factual data verified from spatial, Census, and UDYAM databases")
    calculations: Dict[str, Any] = Field(default_factory=dict, description="Deterministic outputs from financial calculation tool (NO LLM math)")
    estimates: Dict[str, Any] = Field(default_factory=dict, description="Spatial saturation and seasonal operational indicators")
    ai_suggestions: List[str] = Field(default_factory=list, description="Strategic directives, risk mitigations, and operational steps generated by Gemini")

    # Scheme and RAG context
    matched_schemes: List[Dict[str, Any]] = Field(default_factory=list, description="Matched government credit-linked schemes")
    rag_evidence: List[Dict[str, Any]] = Field(default_factory=list, description="Retrieved excerpts from official government scheme guidelines")

    # Verification and auditing
    verification_notes: List[str] = Field(default_factory=list, description="Mandatory official procedural verifications required")
    tool_execution_trace: List[ToolExecutionLog] = Field(default_factory=list, description="Audit trace of all tool calls executed by the agent")
    agent_architecture: str = "LANGCHAIN_GEMINI_MULTI_TOOL_AGENT"

